<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>IczpNet.AbpCommons</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IczpNet.AbpCommons.Application\IczpNet.AbpCommons.Application.csproj" />
    <ProjectReference Include="..\IczpNet.AbpCommons.Domain.Tests\IczpNet.AbpCommons.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="ConfigureAwait.Fody" Version="3.4.1" />
    <PackageReference Update="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
